# Generated by Django 5.2 on 2025-09-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Political', 'Political'), ('Nature', 'Nature'), ('Sports', 'Sports'), ('Food', 'Food')], default='none', max_length=10),
        ),
    ]
