# Generated by Django 6.0.2 on 2026-03-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtrack_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('angry', 'Angry'), ('sad', 'Sad'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('neutral', 'Neutral')], max_length=20),
        ),
    ]
