# Generated by Django 6.0.2 on 2026-03-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtrack_app', '0005_comment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('joy', 'Joy'), ('anger', 'Anger'), ('sad', 'Sad'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('neutral', 'Neutral'), ('disgust', 'Disgust'), ('excitement', 'Excitement'), ('relief', 'Relief'), ('confusion', 'Confusion')], max_length=20),
        ),
    ]
