# Generated by Django 6.0.2 on 2026-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtrack_app', '0006_alter_comment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('Joy', 'Joy'), ('Anger', 'Anger'), ('Sad', 'Sad'), ('Fear', 'Fear'), ('Surprise', 'Surprise'), ('Neutral', 'Neutral'), ('Disgust', 'Disgust'), ('Excitement', 'Excitement'), ('Relief', 'Relief'), ('Confusion', 'Confusion')], max_length=20),
        ),
    ]
