# Generated by Django 5.2.12 on 2026-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtrack_app', '0008_badge_comment_is_reported_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
