# Generated by Django 5.2.12 on 2026-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtrack_app', '0009_userprofile_total_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trending_posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
